### ISSUE TITLE
dynamicProxy issue with interface name overriding

### ISSUE THREAD

**Issue by haggish** [hypfvieh/dbus-java#19]
Hi!
 
I have been using dbus-java 2.* and now experimenting with 3.0 SNAPSHOT. I ran to an issue with code that is getting a DBus object, calling `DBusConnection.dynamicProxy`:

```
org.freedesktop.dbus.exceptions.DBusExecutionException: Invalid arguments
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.freedesktop.dbus.errors.Error.getException(Error.java:150)
	at org.freedesktop.dbus.errors.Error.throwException(Error.java:180)
	at org.freedesktop.dbus.RemoteInvocationHandler.executeRemoteMethod(RemoteInvocationHandler.java:163)
	at org.freedesktop.dbus.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:227)
	at com.sun.proxy.$Proxy37.Connect(Unknown Source)
[...]
```

Cranking up the debug levels I see:

```
2018-06-06 04:27:29 [DBus Worker Thread-3] DEBUG o.f.d.c.impl.DBusConnection - Trying interface org.freedesktop.DBus.Introspectable
2018-06-06 04:27:29 [DBus Worker Thread-3] DEBUG o.f.d.c.impl.DBusConnection - Trying interface org.freedesktop.DBus.Introspectable
2018-06-06 04:27:29 [DBus Worker Thread-3] DEBUG o.f.d.c.impl.DBusConnection - Trying interface net.connman.Service
2018-06-06 04:27:29 [DBus Worker Thread-3] DEBUG o.f.d.c.impl.DBusConnection - Trying interface net.connman.Service
2018-06-06 04:27:29 [DBus Worker Thread-3] DEBUG o.f.d.c.impl.DBusConnection - 
org.freedesktop.dbus.exceptions.DBusException: Could not find an interface to cast to
	at org.freedesktop.dbus.connections.impl.DBusConnection.dynamicProxy(DBusConnection.java:302)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getExportedObject(DBusConnection.java:334)
	at org.freedesktop.dbus.Marshalling.deSerializeParameter(Marshalling.java:502)
	at org.freedesktop.dbus.Marshalling.deSerializeParameters(Marshalling.java:698)
	at org.freedesktop.dbus.connections.AbstractConnection$2.run(AbstractConnection.java:675)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Digging into `dynamicProxy`, I see that it is getting first the object as `Introspectable` and checking if it can load any interfaces that it declares in the introspection XML, then just using the first one. But it does not take into account if someone has overridden the Java package / DBus interface sync with `DBusInterfaceName`. 

I have these overrides in place in every DBus interface I access, and now in 3.0 also the DBus `Introspectable` Java package diverges from the DBus interface name. I guess this has previously worked because `Introspectable` is(?) the interface every DBus object has, and its Java package has been matching the interface name, and you can cast the proxy to another interface. But now `Introspectable` Java package does not match the DBus interface name any more, and the whole thing fails.
 
Does this make any sense? Should there be a mechanism that given ClassNotFoundEx for an introspected IF, tries to check if there is a class annotated with IF name override with matching value? Or in the case no classes matching the interfaces can be found (or actually in _any_ case), just use `Introspectable` since all DBus objects should implement that?

Something along the lines of (`DBusConnection.dynamicProxy:301-`) ?
```
            if (ifcs.size() == 0) {
                //throw new DBusException("Could not find an interface to cast to");
                ifcs.add(Introspectable.class);
            }
```

**Comment by hypfvieh** [comment]
Is this issue resolved now?

**Comment by haggish** [comment]
Yes, it seems to work now without casting problems
